//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Проверочная_работа_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class blood_service
    {
        public int blood { get; set; }
        public Nullable<int> service { get; set; }
        public Nullable<double> result { get; set; }
        public Nullable<System.DateTime> finished { get; set; }
        public Nullable<bool> accepted { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> analyzer { get; set; }
        public Nullable<int> sotrudnik { get; set; }
    
        public virtual analyzer analyzer1 { get; set; }
        public virtual service service1 { get; set; }
        public virtual status status1 { get; set; }
        public virtual user user { get; set; }
    }
}
