//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Проверочная_работа_2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class labEntities : DbContext
    {
        public labEntities()
            : base("name=labEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<analyzer> analyzer { get; set; }
        public virtual DbSet<blood_service> blood_service { get; set; }
        public virtual DbSet<country> country { get; set; }
        public virtual DbSet<incurance> incurance { get; set; }
        public virtual DbSet<patients> patients { get; set; }
        public virtual DbSet<service> service { get; set; }
        public virtual DbSet<social_type> social_type { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<user_type> user_type { get; set; }
    }
}
