//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Проверочная_работа_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class patients
    {
        public int id { get; set; }
        public string full_name { get; set; }
        public string login { get; set; }
        public string pwd { get; set; }
        public string guid { get; set; }
        public string email { get; set; }
        public string social_sec_number { get; set; }
        public string phone { get; set; }
        public Nullable<int> passport_s { get; set; }
        public Nullable<int> passport_n { get; set; }
        public Nullable<System.DateTime> birthdate_timestamp { get; set; }
        public string ipadress { get; set; }
        public string ua { get; set; }
        public Nullable<int> country { get; set; }
        public Nullable<int> social_type { get; set; }
        public string ein { get; set; }
        public Nullable<int> insurance_name { get; set; }
    
        public virtual country country1 { get; set; }
        public virtual incurance incurance { get; set; }
        public virtual social_type social_type1 { get; set; }
    }
}
